FROM ruby:4.0.1-slim-bookworm
RUN apt-get update -qq && apt-get install --no-install-recommends -y build-essential git curl libpq-dev libyaml-dev pkg-config postgresql-client && rm -rf /var/lib/apt/lists /var/cache/apt/archives
WORKDIR /rails
ENV BUNDLE_PATH="/usr/local/bundle" PATH="/usr/local/bundle/bin:$PATH"
COPY Gemfile Gemfile.lock ./
RUN bundle install
EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
