default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: stock_screener_development
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
    database: stock_screener_development_queue
    migrations_paths: db/queue_migrate
test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>
  database: stock_screener_test
production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
