development: &tasks
  expire_reversals:
    class: ExpireReversalsJob
    schedule: every minute
  refresh_signal_reactions:
    class: RefreshSignalReactionsJob
    schedule: every minute
  refresh_history:
    class: RefreshHistoryJob
    schedule: every hour
  prune_minutes:
    command: "MarketMinute.where('time < ?', 7.days.ago).delete_all"
    schedule: every day at 3am
production:
  <<: *tasks
